[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Nope when Invisible sold
[[patches]]
[patches.pattern]
target = "card.lua"
pattern = "if self.ability.name == 'Invisible Joker' and (self.ability.invis_rounds >= self.ability.extra) and not context.blueprint then"
position = 'after'
payload = '''
	if G.GAME and G.GAME.bad_nope then
		G.GAME.bad_nope_blocked = true
		return
	end
'''
match_indent = true
