[manifest]
version = "1.0.0"
dump_lua = true
priority = 1

# Chance roll for acquiring tags
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "add_tag(_tag.config.ref_table)"
position = 'at'
payload = '''
	if SMODS.pseudorandom_probability(_tag.config.ref_table, 'bad_tag_nope', 1, 2) then 
		add_tag(_tag.config.ref_table)
	else
		G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.4, func = function()
		attention_text({
			text = localize('k_nope_ex'),
			scale = 1.3, 
			hold = 1.4,
			major = G.play,
			backdrop_colour = G.C.SECONDARY_SET.Tarot,
			align = (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) and 'tm' or 'cm',
			offset = {x = 0, y = (G.STATE == G.STATES.TAROT_PACK or G.STATE == G.STATES.SPECTRAL_PACK or G.STATE == G.STATES.SMODS_BOOSTER_OPENED) and -0.2 or 0},
			silent = true
		})
		G.E_MANAGER:add_event(Event({trigger = 'after', delay = 0.06*G.SETTINGS.GAMESPEED, blockable = false, blocking = false, func = function()
			play_sound('tarot2', 0.76, 0.4);return true end}))
		play_sound('tarot2', 1, 0.4)
		return true 
	end}))
	end
'''
match_indent = true

# text to show 1 in 2 chance
[[patches]]
[patches.pattern]
target = "functions/UI_definitions.lua"
pattern = "{n=G.UIT.T, config={text = localize('b_skip_blind'), scale = 0.4, colour = G.C.UI.TEXT_INACTIVE}}"
position = 'at'
payload = '''
{n=G.UIT.R, config={align = "cm", colour = G.C.CLEAR}, nodes={
	{n=G.UIT.O, config={object = DynaText({string = localize('b_skip_blind'), scale = 0.4, colours = {G.C.UI.TEXT_INACTIVE}, silent = true, float = false}) }},
}},
{n=G.UIT.R, config={align = "cm", colour = G.C.CLEAR}, nodes={
	{n=G.UIT.O, config={object = DynaText({string = {{ref_table = G.GAME.probabilities, ref_value = 'normal', suffix = localize('b_skip_blind_info'), scale = 1}}, scale = 0.225, colours = {G.C.UI.TEXT_INACTIVE}, silent = true, float = false}) }},
}}
'''
match_indent = true

# two fixes for previous patch because Thunk hardcoded the UI tree path
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "_tag.children[2].children[1].config.colour = G.C.UI.TEXT_LIGHT"
position = 'at'
payload = '''
_tag.children[2].children[1].children[1].config.object.colours = {G.C.UI.TEXT_LIGHT}
_tag.children[2].children[2].children[1].config.object.colours = {G.C.UI.TEXT_LIGHT}
'''
match_indent = true
[[patches]]
[patches.pattern]
target = "functions/button_callbacks.lua"
pattern = "_tag.children[2].children[1].config.colour = G.C.UI.TEXT_INACTIVE"
position = 'at'
payload = '''
_tag.children[2].children[1].children[1].config.object.colours = {G.C.UI.TEXT_INACTIVE}
_tag.children[2].children[2].children[1].config.object.colours = {G.C.UI.TEXT_INACTIVE}
'''
match_indent = true
